spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    # url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:mysql://localhost:3306/user_db
    # url: jdbc:mariadb://localhost:3307/soisota?useLegacyDatetimeCode=false&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    # url: jdbc:mariadb://25.7.200.76:3307/soingu?useLegacyDatetimeCode=false&serverTimezone=UTC
    #url: jdbc:mariadb://localhost:3307/soingu?useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mariadb://25.7.200.76:3307/s_bill?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: cmis1234
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto: update
      #ddl-auto: none
      #naming:
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        id:
          new_generator_mappings: false
    show-sql: false

server:
  port: 8088 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlfArQiQt7HOVsMG0MTGqYG2aOBrWspb+nXYswA9Ft9Bqm2RslDdoz4G8KuE9cJ5ZEd6m2tI1Q1qrkVBao/9MB6+npXwtETt4V72YGB6SvlsHRBn7x2EiY5igje0mT6CiJI//AtcFIxFYv4rn7sFngDtp9N6L+DDq/c8xybsQfphgmo/mUX9pL3ei8SKODjz8wJy+9GjRH0964RpmTEG2D7zyDjit36oU0rN4Ad6UPFe6D9xdeqQDuVDJG9G6zObsPlaiVzLmaVZgYnLRkhM3LXssjwRvO6ZQRJe+r/MHt0L/+KwKzQ7EXfJG2uP+3p61bzgsMt0CxsCo7pKE6k81ywIDAQAB
      private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCV8CtCJC3sc5WwwbQxMapgbZo4Gtaylv6ddizAD0W30GqbZGyUN2jPgbwq4T1wnlkR3qba0jVDWquRUFqj/0wHr6elfC0RO3hXvZgYHpK+WwdEGfvHYSJjmKCN7SZPoKIkj/8C1wUjEVi/iufuwWeAO2n03ov4MOr9zzHJuxB+mGCaj+ZRf2kvd6LxIo4OPPzAnL70aNEfT3rhGmZMQbYPvPIOOK3fqhTSs3gB3pQ8V7oP3F16pAO5UMkb0brM5uw+VqJXMuZpVmBictGSEzcteyyPBG87plBEl76v8we3Qv/4rArNDsRd8kba4/7enrVvOCwy3QLGwKjukoTqTzXLAgMBAAECggEAW0Oj4Q+KkHlObReKqcL0VNuB2pKjinMUKh4rYQAqzJbkvQ8kdBdCCcSLF4KgVjNcPd9Lqrf2ybef5MSHV3lm+uq1Xao2+F09hBKYSF4brhhUVOSH97UtLHhTifAGuMMqzpyDeWQN8Wl2nqhbQl2gtVH0zaLEid6kurbqNENT5+m7PRebxEzk1NYBMPoULYB01c83zrfSn+Awbmho0wXmmx4d25bdBeaSFqv/9Vu3jGXgr88TSO7/OEzzryafp9M7RsluILvIgjiaa1g5+c3bHkyHLAQoCv0rch0BVfNhnnZjQGiOvH143WYBID3uoVIGPNGbOLPTFYura2KReEHNcQKBgQD/XmFhak1pTcP/j7mo6jTd/1KXJ5JhtDOCtnBXwg1G0GOfHJzulkVo/u3YDV8n948ISaPTFztNjW0Qy85uGdI29aIvgg/FqUhX1aMMv/pH0Tno6vlpSkaNAsoMzp4eiypJ+flhUNx6h7NDucr65s1TiN/x9M6ysglbOg0BA03PKQKBgQCWTxAdLytrt2e00SLv4uWFc8+dsjus4W+jfZEAXgWt2zmdh5sqa/eEJxvg08BbDMGt+IKDrPH5aXbXSgK0OuAq4mSLg19hUqyoIKw7r2l2Tmoo69pGjZ6JKgRzz3/SJ1qdKr4KEWoeSEDvIX0isyPhzsfXFxn5iensxmuE2Muf0wKBgQDK19QwRfkRcTUDlc2ar9aok/utl0A+HZ5g8LuR6dET88l+BINfPLwLp5uTZyOzon/ZzGy16xkvA+yjT9A8QoRpJXnblMskbc/J/SeTpBaQ30/JhIPyr44UyidmPuT4TACeXFJLi6hmJ84sOLNT0us7tFh2X8ejx6mI7jaQHGi86QKBgA3MynzzdLgaCaJ3RQ7jNRFwlZIz5/iyZe6Lu8Fd4IWayApnhd56NSpj8NJOfq2dWTbgxxLR0RGGFkwj1mW3thcZ3ANXF223CnURMt7z9unOvz5skQjDPdf4DJqZZXHk/RPK9dG00ZpgJd4OpA+IhPXZZ02fKFpZyCld+kcjJGbTAoGAP1R5oXpZwkBMiLHQukPhmjkF0H1yMMsnKX/A7M3FlLV4eUWPCMFmuCyNdKnOh7si88z5IWtsrxjVYMmZGZQC2fMMeHzevX5ynUSj1UYsfHi7KtPyYAZaAZAbxvPnOsvT8Nfx+3DYaOIeDjMXN2GvtQ0ovK5+VTwjqQ9vbE9UexM=
      secret-key: RVZOSUNUMTFDVUFCQUM=
      expire-length: 86400000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  getInfoCurrentUser: Returns current user's data
  register: Create user and return username for next login

APIService:
  SmsEmailService: http://10.1.117.239:9000/smsemail/


